ignored = [
  "github.com/mattn/go-gtk/gdk"
]

[[constraint]]
  branch = "master"
  name = "github.com/AllenDang/w32"

[[constraint]]
  name = "github.com/mattn/go-gtk"
  revision = "5a311a1830abecc430a6a598b24094f69d907e96"

[[constraint]]
  branch = "master"
  name = "github.com/skelterjohn/go.wde"
